%% Reproduce calibration outputs for dissertation
% Adjust paths if needed
csvPath = 'data/continuous_factory_process.csv';

addpath(genpath('src'));

calib = calibrate_continuous_flow(csvPath, ...
    'FigurePath','output/figures', ...
    'ConfigPath','config', ...
    'ResampleMin',1, ...
    'SpecBandMethod','MAD', ...
    'SpecK',3, ...
    'MinStopSamples',2, ...
    'SmoothWin',3);

disp(calib);
